name: Publish Docker Image
on:
  release:
    types: [published]
env:
  IMAGE: ${{ github.repository }}
  VERSION: ${{ github.event.release.tag_name }}
jobs:
  push_to_registry:
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log into docker hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

      - name: Build docker image
        run: docker build . --file Dockerfile --tag $IMAGE

      - name: Push image to docker hub
        run: |
          echo "IMAGE=$IMAGE"
          echo "VERSION=$VERSION"
          docker tag $IMAGE $IMAGE:$VERSION
          docker push $IMAGE:$VERSION
          docker tag $IMAGE $IMAGE:latest
          docker push $IMAGE:latest
